# Generated by Django 2.0.13 on 2019-03-09 20:48

import compress_storage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190310_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=compress_storage.models.ZipFileField(upload_to='books/pdfs/'),
        ),
    ]
