# Generated by Django 2.0.13 on 2019-03-09 22:17

import cloud.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190310_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(upload_to=cloud.core.models.get_file_path),
        ),
    ]
